//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CLIESC_ConUni_SOAPDOTNET_GR03.ConversionServiceRef {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConvertOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertUnitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::CLIESC_ConUni_SOAPDOTNET_GR03.Properties.Settings.Default.CLIESC_ConUni_SOAPDOTNET_GR03_ConversionServiceRef_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConvertCompletedEventHandler ConvertCompleted;
        
        /// <remarks/>
        public event ConvertUnitCompletedEventHandler ConvertUnitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/Convert", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ConversionResponse Convert([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ConversionRequest request) {
            object[] results = this.Invoke("Convert", new object[] {
                        request});
            return ((ConversionResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService/ConvertUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double ConvertUnit(double value, string inUnit, string outUnit) {
            object[] results = this.Invoke("ConvertUnit", new object[] {
                        value,
                        inUnit,
                        outUnit});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertAsync(ConversionRequest request) {
            this.ConvertAsync(request, null);
        }
        
        /// <remarks/>
        public void ConvertAsync(ConversionRequest request, object userState) {
            if ((this.ConvertOperationCompleted == null)) {
                this.ConvertOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertOperationCompleted);
            }
            this.InvokeAsync("Convert", new object[] {
                        request}, this.ConvertOperationCompleted, userState);
        }
        
        private void OnConvertOperationCompleted(object arg) {
            if ((this.ConvertCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertCompleted(this, new ConvertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public void ConvertUnitAsync(double value, string inUnit, string outUnit) {
            this.ConvertUnitAsync(value, inUnit, outUnit, null);
        }
        
        /// <remarks/>
        public void ConvertUnitAsync(double value, string inUnit, string outUnit, object userState) {
            if ((this.ConvertUnitOperationCompleted == null)) {
                this.ConvertUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertUnitOperationCompleted);
            }
            this.InvokeAsync("ConvertUnit", new object[] {
                        value,
                        inUnit,
                        outUnit}, this.ConvertUnitOperationCompleted, userState);
        }
        
        private void OnConvertUnitOperationCompleted(object arg) {
            if ((this.ConvertUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertUnitCompleted(this, new ConvertUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFService.Models")]
    public partial class ConversionRequest {
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private double longitude2Field;
        
        private bool longitude2FieldSpecified;
        
        private double massKgField;
        
        private bool massKgFieldSpecified;
        
        private double temperatureCelsiusField;
        
        private bool temperatureCelsiusFieldSpecified;
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude2 {
            get {
                return this.longitude2Field;
            }
            set {
                this.longitude2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Longitude2Specified {
            get {
                return this.longitude2FieldSpecified;
            }
            set {
                this.longitude2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double MassKg {
            get {
                return this.massKgField;
            }
            set {
                this.massKgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MassKgSpecified {
            get {
                return this.massKgFieldSpecified;
            }
            set {
                this.massKgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double TemperatureCelsius {
            get {
                return this.temperatureCelsiusField;
            }
            set {
                this.temperatureCelsiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemperatureCelsiusSpecified {
            get {
                return this.temperatureCelsiusFieldSpecified;
            }
            set {
                this.temperatureCelsiusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFService.Models")]
    public partial class CoordinateDMS {
        
        private int degreesField;
        
        private bool degreesFieldSpecified;
        
        private int hemisphereField;
        
        private bool hemisphereFieldSpecified;
        
        private int minutesField;
        
        private bool minutesFieldSpecified;
        
        private double secondsField;
        
        private bool secondsFieldSpecified;
        
        /// <remarks/>
        public int Degrees {
            get {
                return this.degreesField;
            }
            set {
                this.degreesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DegreesSpecified {
            get {
                return this.degreesFieldSpecified;
            }
            set {
                this.degreesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Hemisphere {
            get {
                return this.hemisphereField;
            }
            set {
                this.hemisphereField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HemisphereSpecified {
            get {
                return this.hemisphereFieldSpecified;
            }
            set {
                this.hemisphereFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinutesSpecified {
            get {
                return this.minutesFieldSpecified;
            }
            set {
                this.minutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SecondsSpecified {
            get {
                return this.secondsFieldSpecified;
            }
            set {
                this.secondsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WCFService.Models")]
    public partial class ConversionResponse {
        
        private CoordinateDMS latitudeDMSField;
        
        private double latitudeDecimalField;
        
        private bool latitudeDecimalFieldSpecified;
        
        private double latitudeRadiansField;
        
        private bool latitudeRadiansFieldSpecified;
        
        private CoordinateDMS longitude2DMSField;
        
        private double longitude2DecimalField;
        
        private bool longitude2DecimalFieldSpecified;
        
        private double longitude2RadiansField;
        
        private bool longitude2RadiansFieldSpecified;
        
        private CoordinateDMS longitudeDMSField;
        
        private double longitudeDecimalField;
        
        private bool longitudeDecimalFieldSpecified;
        
        private double longitudeRadiansField;
        
        private bool longitudeRadiansFieldSpecified;
        
        private double massGField;
        
        private bool massGFieldSpecified;
        
        private double massKgField;
        
        private bool massKgFieldSpecified;
        
        private double massLbField;
        
        private bool massLbFieldSpecified;
        
        private double temperatureCelsiusField;
        
        private bool temperatureCelsiusFieldSpecified;
        
        private double temperatureFahrenheitField;
        
        private bool temperatureFahrenheitFieldSpecified;
        
        private double temperatureKelvinField;
        
        private bool temperatureKelvinFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CoordinateDMS LatitudeDMS {
            get {
                return this.latitudeDMSField;
            }
            set {
                this.latitudeDMSField = value;
            }
        }
        
        /// <remarks/>
        public double LatitudeDecimal {
            get {
                return this.latitudeDecimalField;
            }
            set {
                this.latitudeDecimalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeDecimalSpecified {
            get {
                return this.latitudeDecimalFieldSpecified;
            }
            set {
                this.latitudeDecimalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double LatitudeRadians {
            get {
                return this.latitudeRadiansField;
            }
            set {
                this.latitudeRadiansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeRadiansSpecified {
            get {
                return this.latitudeRadiansFieldSpecified;
            }
            set {
                this.latitudeRadiansFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CoordinateDMS Longitude2DMS {
            get {
                return this.longitude2DMSField;
            }
            set {
                this.longitude2DMSField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude2Decimal {
            get {
                return this.longitude2DecimalField;
            }
            set {
                this.longitude2DecimalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Longitude2DecimalSpecified {
            get {
                return this.longitude2DecimalFieldSpecified;
            }
            set {
                this.longitude2DecimalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double Longitude2Radians {
            get {
                return this.longitude2RadiansField;
            }
            set {
                this.longitude2RadiansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Longitude2RadiansSpecified {
            get {
                return this.longitude2RadiansFieldSpecified;
            }
            set {
                this.longitude2RadiansFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CoordinateDMS LongitudeDMS {
            get {
                return this.longitudeDMSField;
            }
            set {
                this.longitudeDMSField = value;
            }
        }
        
        /// <remarks/>
        public double LongitudeDecimal {
            get {
                return this.longitudeDecimalField;
            }
            set {
                this.longitudeDecimalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeDecimalSpecified {
            get {
                return this.longitudeDecimalFieldSpecified;
            }
            set {
                this.longitudeDecimalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double LongitudeRadians {
            get {
                return this.longitudeRadiansField;
            }
            set {
                this.longitudeRadiansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeRadiansSpecified {
            get {
                return this.longitudeRadiansFieldSpecified;
            }
            set {
                this.longitudeRadiansFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double MassG {
            get {
                return this.massGField;
            }
            set {
                this.massGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MassGSpecified {
            get {
                return this.massGFieldSpecified;
            }
            set {
                this.massGFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double MassKg {
            get {
                return this.massKgField;
            }
            set {
                this.massKgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MassKgSpecified {
            get {
                return this.massKgFieldSpecified;
            }
            set {
                this.massKgFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double MassLb {
            get {
                return this.massLbField;
            }
            set {
                this.massLbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MassLbSpecified {
            get {
                return this.massLbFieldSpecified;
            }
            set {
                this.massLbFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double TemperatureCelsius {
            get {
                return this.temperatureCelsiusField;
            }
            set {
                this.temperatureCelsiusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemperatureCelsiusSpecified {
            get {
                return this.temperatureCelsiusFieldSpecified;
            }
            set {
                this.temperatureCelsiusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double TemperatureFahrenheit {
            get {
                return this.temperatureFahrenheitField;
            }
            set {
                this.temperatureFahrenheitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemperatureFahrenheitSpecified {
            get {
                return this.temperatureFahrenheitFieldSpecified;
            }
            set {
                this.temperatureFahrenheitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double TemperatureKelvin {
            get {
                return this.temperatureKelvinField;
            }
            set {
                this.temperatureKelvinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TemperatureKelvinSpecified {
            get {
                return this.temperatureKelvinFieldSpecified;
            }
            set {
                this.temperatureKelvinFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ConvertCompletedEventHandler(object sender, ConvertCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConversionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConversionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    public delegate void ConvertUnitCompletedEventHandler(object sender, ConvertUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9221.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591